/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CompilerUnitTester */

#ifndef _Included_CompilerUnitTester
#define _Included_CompilerUnitTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CompilerUnitTester
 * Method:    openj9_compiler_handshake
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CompilerUnitTester_openj9_1compiler_1handshake
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
